In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('melb_data.csv')
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [4]:
cols_to_use = ['Suburb', 'Rooms', 'Type', 'Method', 'SellerG', 'Regionname', 'Propertycount', 
               'Distance', 'CouncilArea', 'Bedroom2', 'Bathroom', 'Car', 'Landsize', 'BuildingArea', 'Price']
df = df[cols_to_use]
df.head()

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,2.0,1.0,1.0,202.0,NaN,1480000.0
1,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,2.0,1.0,0.0,156.0,79.0,1035000.0
2,Abbotsford,3,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,3.0,2.0,0.0,134.0,150.0,1465000.0
3,Abbotsford,3,h,PI,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,3.0,2.0,1.0,94.0,NaN,850000.0
4,Abbotsford,4,h,VB,Nelson,Northern Metropolitan,4019.0,2.5,Yarra,3.0,1.0,2.0,120.0,142.0,1600000.0

In [5]:
df.isna().sum()

Suburb              0
Rooms               0
Type                0
Method              0
SellerG             0
Regionname          0
Propertycount       0
Distance            0
CouncilArea      1369
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea     6450
Price               0
dtype: int64

In [6]:
df.shape

(13580, 15)

In [7]:
df['BuildingArea'] = df['BuildingArea'].fillna(df.BuildingArea.mean())

In [8]:
df.dropna(inplace = True)

In [9]:
df.head()

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,2.0,1.0,1.0,202.0,151.96765,1480000.0
1,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,2.0,1.0,0.0,156.0,79.00000,1035000.0
2,Abbotsford,3,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,3.0,2.0,0.0,134.0,150.00000,1465000.0
3,Abbotsford,3,h,PI,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,3.0,2.0,1.0,94.0,151.96765,850000.0
4,Abbotsford,4,h,VB,Nelson,Northern Metropolitan,4019.0,2.5,Yarra,3.0,1.0,2.0,120.0,142.00000,1600000.0

In [10]:
df.shape

(12211, 15)

In [11]:
df.drop(['Suburb', 'Type', 'Method', 'SellerG', 'Regionname', 'CouncilArea'], axis = 'columns')

,Rooms,Propertycount,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,2,4019.0,2.5,2.0,1.0,1.0,202.0,151.96765,1480000.0
1,2,4019.0,2.5,2.0,1.0,0.0,156.0,79.00000,1035000.0
2,3,4019.0,2.5,3.0,2.0,0.0,134.0,150.00000,1465000.0
3,3,4019.0,2.5,3.0,2.0,1.0,94.0,151.96765,850000.0
4,4,4019.0,2.5,3.0,1.0,2.0,120.0,142.00000,1600000.0
...,...,...,...,...,...,...,...,...,...
12208,3,6380.0,6.8,3.0,1.0,0.0,296.0,151.96765,1285000.0
12209,2,4380.0,4.6,2.0,1.0,1.0,0.0,61.60000,560000.0
12210,3,2940.0,25.5,3.0,2.0,2.0,400.0,151.96765,525300.0
12211,2,6543.0,6.3,2.0,1.0,2.0,269.0,151.96765,750000.0
12212,6,6543.0,6.3,6.0,3.0,2.0,1087.0,388.50000,2450000.0

In [12]:
df = pd.get_dummies(df)
df.head()

,Rooms,Propertycount,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price,Suburb_Abbotsford,...,CouncilArea_Moreland,CouncilArea_Nillumbik,CouncilArea_Port Phillip,CouncilArea_Stonnington,CouncilArea_Unavailable,CouncilArea_Whitehorse,CouncilArea_Whittlesea,CouncilArea_Wyndham,CouncilArea_Yarra,CouncilArea_Yarra Ranges
0,2,4019.0,2.5,2.0,1.0,1.0,202.0,151.96765,1480000.0,1,...,0,0,0,0,0,0,0,0,1,0
1,2,4019.0,2.5,2.0,1.0,0.0,156.0,79.00000,1035000.0,1,...,0,0,0,0,0,0,0,0,1,0
2,3,4019.0,2.5,3.0,2.0,0.0,134.0,150.00000,1465000.0,1,...,0,0,0,0,0,0,0,0,1,0
3,3,4019.0,2.5,3.0,2.0,1.0,94.0,151.96765,850000.0,1,...,0,0,0,0,0,0,0,0,1,0
4,4,4019.0,2.5,3.0,1.0,2.0,120.0,142.00000,1600000.0,1,...,0,0,0,0,0,0,0,0,1,0

In [13]:
X = df.drop(['Price'], axis = 'columns')
y = df['Price']

In [14]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.3)

In [15]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(train_X, train_y)

In [16]:
reg.score(train_X, train_y)

0.7127594917566731

In [17]:
reg.score(test_X, test_y)

-49737708790.3959

In [18]:
from sklearn import linear_model
lasso_reg = linear_model.Lasso(alpha = 50, max_iter = 100, tol = 0.1)
lasso_reg.fit(train_X, train_y)

Lasso(alpha=50, max_iter=100, tol=0.1)

In [19]:
lasso_reg.score(test_X, test_y)

0.6526668677329848

In [20]:
lasso_reg.score(train_X, train_y)

0.7087458572177908

In [21]:
from sklearn import linear_model
ridge_reg = linear_model.Ridge(alpha = 50, max_iter = 100, tol = 0.1)
ridge_reg.fit(train_X, train_y)

Ridge(alpha=50, max_iter=100, tol=0.1)

In [22]:
ridge_reg.score(test_X, test_y)

0.6506834554417511

In [23]:
ridge_reg.score(train_X, train_y)

0.6796056728853327